library(wordcloud)
corpus.matrix <- as.matrix(reviewDtmCompact)
corpus.sorted <- sort(colSums(corpus.matrix), decreasing=TRUE)
terms <- names(corpus.sorted)
terms.df <- data.frame(word=terms, freq=corpus.sorted)
wordcloud(terms.df$word, colors=c(3,4), random.color=FALSE, terms.df$freq, min.freq=35000)
rm(corpus.matrix)
rm(corpus.sorted)
rm(terms)
rm(terms.df)